# Smart meter ID
device_id: "1SAG1100000292"

# Detector configuration
detector:
  method: "HART"
  event_threshold: 50
  state_threshold: 50

# Source MQTT broker
client:
  host: "localhost"
  port: 1883

# Sink Database
db:
  host: "localhost"
  port: 5432
  database: "premises"
  user: "postgres"
  password: "password"

# Sink MQTT broker
mqtt:
  host: "localhost"
  port: 1883
