{
 "title": "Event detection",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "METERS",
    "label": "Meters",
    "query": "SELECT DISTINCT(device_id) FROM elec_measurement;"
   }
  ]
 },
 "panels": [
  {
   "title": "Grid Power",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value AS \"P+\"\nFROM elec_measurement\nWHERE\n  $__timeFilter(\"time\") AND\n  obis_name = 'P+' AND\n  device_id = '$METERS' \nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value AS \"P-\"\nFROM elec_measurement\nWHERE\n  $__timeFilter(\"time\") AND\n  obis_name = 'P-' AND\n  device_id = '$METERS' \nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  post_state/1000 AS \"GOF-VOTING\"\nFROM event\nWHERE\n  $__timeFilter(\"time\") AND\n  method = 'GOF-VOTING' AND\n  device_id = '$METERS' \nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  post_state/1000 AS \"GLR-VOTING\"\nFROM event\nWHERE\n  $__timeFilter(\"time\") AND\n  method = 'GLR-VOTING' AND\n  device_id = '$METERS' \nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  post_state/1000 AS \"HART\"\nFROM event\nWHERE\n  $__timeFilter(\"time\") AND\n  method = 'HART-None' AND\n  device_id = '$METERS' \nORDER BY 1"
    }
   ]
  },
  {
   "title": "GOF-VOTING",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  transient AS \"Transient\"\nFROM event\nWHERE\n  $__timeFilter(\"time\") AND\n  method = 'GOF-VOTING' AND\n  device_id = '$METERS' \nORDER BY 1 DESC"
    }
   ]
  },
  {
   "title": "GLR-VOTING",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  transient AS \"Transient\"\nFROM event\nWHERE\n  $__timeFilter(\"time\") AND\n  method = 'GLR-VOTING' AND\n  device_id = '$METERS' \nORDER BY 1 DESC"
    }
   ]
  },
  {
   "title": "HART",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  transient AS \"Transient\"\nFROM event\nWHERE\n  $__timeFilter(\"time\") AND\n  method = 'HART-None' AND\n  device_id = '$METERS' \nORDER BY 1 DESC"
    }
   ]
  },
  {
   "title": "Grid Power",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value AS \"P+\"\nFROM elec_measurement\nWHERE\n  $__timeFilter(\"time\") AND\n  obis_name = 'P+' AND\n  device_id = '$METERS' \nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value AS \"P-\"\nFROM elec_measurement\nWHERE\n  $__timeFilter(\"time\") AND\n  obis_name = 'P-' AND\n  device_id = '$METERS' \nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  post_state/1000 AS \"GOF-VOTING\"\nFROM event\nWHERE\n  $__timeFilter(\"time\") AND\n  method = 'GOF-VOTING' AND\n  device_id = '$METERS' \nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  post_state/1000 AS \"GLR-VOTING\"\nFROM event\nWHERE\n  $__timeFilter(\"time\") AND\n  method = 'GLR-VOTING' AND\n  device_id = '$METERS' \nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  post_state/1000 AS \"HART\"\nFROM event\nWHERE\n  $__timeFilter(\"time\") AND\n  method = 'HART-None' AND\n  device_id = '$METERS' \nORDER BY 1"
    }
   ]
  }
 ]
}